# TWRP
BOARD_HAS_NO_REAL_SDCARD := true
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_NTFS_3G := true
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TARGET_RECOVERY_QCOM_RTC_FIX := true
#TW_DEVICE_VERSION := 2
